name: update keys

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      jsin:
        description: '选择要运行的插件'
        required: true
        default: 'manwa'
    
env:
 THEJS: ${{ github.event.inputs.jsin }}
 MATRIX_DIRECTORY: ${GITHUB_WORKSPACE}
 TZ: Asia/Shanghai
 
jobs:
  updateKeys:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@main
      
     - name: download decrypted js from website
       run: |
        #todo

     - name: extra keys from js file
       run: |
        node main.js decrypted.js $THEJS.js
          
     - name: upload js keys
       uses: actions/upload-artifact@main
       with:
         name: ${{ env.THEJS}}
         path: ${{ env.MATRIX_DIRECTORY }}/*.json
